name: Notification Pipeline
on:
  schedule:
    - cron: "*/30 0-10 * * 1-5"
env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
  CYPRESS_SSO_NRP: ${{ vars.SSO_NRP }}
  CYPRESS_SSO_PASSWORD: ${{ secrets.SSO_PASSWORD }}

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v6
        name: Scrapping data from SIAKAD
      - name: Upload data file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-data
          path: dist/

  send_notification:
    needs: get_data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download static json artifact
        uses: actions/download-artifact@v3
        with:
          name: my-data
          path: dist/
      - name: Send notification via telegram
        run: |
          npm install
          npm run start
